### ISSUE TITLE
Change personal picture for the 2018 edition

### ISSUE THREAD

**Issue by rememberYou** [oSoc18/website#22]
Hi, 

Sorry to open an issue for so little, would it be possible to replace my photograph on the [site](http://2018.summerofcode.be/2018.html)?

Thank you!

**Comment by mietcls** [comment]
Hi Terencio!

You can always add it yourself by doing a pull request!

Thank you

Kind regards
Miet

Miet Claes • miet.be • 0478 451 496

On Thu, Jul 26, 2018 at 9:19 AM, Terencio Agozzino <notifications@github.com

**Comment by rememberYou** [comment]
Alright, thank you.
