### ISSUE TITLE
Partners are not displayed in firefox

### ISSUE THREAD

**Issue by archived-m** [oSoc18/website#38]
Partners aren't displayed on the companies page. I suspect this is an svg problem

**Comment by mietcls** [comment]
Hmm, @elroyK You've been tinkering with it last summer, any ideas?

**Comment by elroyK** [comment]
I just looked around during my lunch break and as I understand it, Firefox's new CSS rules are more strict than before and than other browsers. To display images, you have to give them a width or a height, no matter if you have max- and min- width and height set. So add a CSS rule with a width or a height for the partner images and it'll work (I've tried in the Dev Tools but don't have time to do it and commit and everything)
Hope it helps :) @MichielLeyman @mietcls

**Comment by mietcls** [comment]
Thank you @elroyK ! Enjoy the work, I might be able to look into it some time in december or januari.

**Comment by archived-m** [comment]
Fixed in every browser in #39 
Thanks @elroyK
