### ISSUE TITLE
google map on 'where' section in 'FAQ'

### ISSUE THREAD

**Issue by xivk** [oSoc18/website#5]
There is a google map on the where section of the FAQ page.

We can replace this:
https://github.com/oSoc18/website/blob/master/faq.html#L143
and this:
https://github.com/oSoc18/website/blob/master/faq.html#L158

**Comment by jbelien** [comment]
I'll take care of it 🎉

**Comment by jbelien** [comment]
Done : #6 !
I have a really shitty internet connection here so I took the easiest way (replace Google Maps *iframe* by OpenStreetMap *iframe*).
If needed I can do better when back in Brussels :)
